### ISSUE TITLE
I have no the jdk8-classlist.map,android-sdk-classlist.map,android-support-classlist.map, how can i get that!

### ISSUE THREAD

**Issue by baiyunping333** [droidefense/engine#24]
It's so sad that I have no the jdk8-classlist.map,android-sdk-classlist.map,android-support-classlist.map, how can i get that! Can any one help me?

**Comment by zerjioang** [comment]
Hi baiyunping333, sorry for the inconvenience, let me upload them correctly again

**Comment by zerjioang** [comment]
H baiyunping333 ,
Files are succesfully uploaded on resources folder. You might need to reference them using that new path.
update your git to have them all.

Thanks for letting me know this issue.
