### ISSUE TITLE
Cant find  droidefense-cli-1.0-SNAPSHOT.jar

### ISSUE THREAD

**Issue by gbiagomba** [droidefense/engine#39]
1. **droidefense version (`java -jar droidefense-cli-1.0-SNAPSHOT.jar -v`)**

```
https://github.com/droidefense/engine/tree/0.1-unstable
```

2. **Executed commands with arguments**

```
[https://github.com/gbiagomba/Security-Tools/blob/master/EngineLogOutput.txt](url)

```

2. **Operating System (Mac, Linux, Windows, etc)**

```
Kali Linux 2017.3
```

3. **APK from? (Playstore, ROM, Other)**

```
N/A
```

### Java JVM Stacktrace Log

```
Include Java JVM Stacktrace Log here if exist
```

### Steps to Reproduce

```
Include steps to reproduce the error here
```

### Current output

```
Include current result here
```

### Expected output

```
Include expected result here
```

**Comment by zerjioang** [comment]
Hi,

If you just cloned the repository...have you check building instructions? Anyway, if you dont see any .jar file, try executing build.sh script to compile the application from latest changes.

But, if you downloaded from Github releases version **0.1-unstable** you will find a *.jar file called **droidefense.-0.1-unstable-alpha.jar**, as shown in following image

![image](https://user-images.githubusercontent.com/6706342/34225984-87b79d68-e5c8-11e7-8ca3-85c22b632f4f.png)

and then, you can launch

```bash
java -jar droidefense.-0.1-unstable-alpha.jar -v
```

**Comment by zerjioang** [comment]
I also checked out your attached log file and its seem the jar file is saved in this path:

```
/opt/TEST/engine/target/engine-1.0-SNAPSHOT-jar-with-dependencies.jar
```

Can you check that too?

**Comment by gbiagomba** [comment]
Hello @zerjioang 

Apologies for the tardy response but I think I figured it out but I forgot to close the comment but thank you for helping!

**Comment by gbiagomba** [comment]
root@GBiagomba-Kali:/opt/TEST/engine/target# java -jar droidefense-jar-with-dependencies.jar -v
2018-01-11 13:13:19 INFO  [main] INFO:27 - System detected is Unix
2018-01-11 13:13:19 ERROR [main] ERROR:40 - Environment not ready
2018-01-11 13:13:19 ERROR [main] ERROR:40 - Configuration file (/root/droidefense/config/config.linux.json) not found under expected folder
2018-01-11 13:13:19 ERROR [main] ERROR:40 - Please, check a valid .json file exists before executing the scan
2018-01-11 13:13:19 DEBUG [main] DEBUG:20 - Creating default config.json file...
2018-01-11 13:13:19 DEBUG [main] DEBUG:20 - Creating default config file at /root/droidefense/config/config.linux.json
2018-01-11 13:13:19 ERROR [main] ERROR:40 - Could not read from specified URL: config/config.json
2018-01-11 13:13:19 INFO  [main] INFO:27 - Configuration file succesfully created
2018-01-11 13:13:19 INFO  [main] INFO:27 - Please, configure it and lauch droidefense again


root@GBiagomba-Kali:/opt/TEST/engine/target# java -jar droidefense-jar-with-dependencies.jar 
2018-01-11 13:13:35 INFO  [main] INFO:27 - System detected is Unix


________               .__    .___      _____                            
\______ \_______  ____ |__| __| _/_____/ ____\____   ____   ______ ____  
 |    |  \_  __ \/  _ \|  |/ __ |/ __ \   __\/ __ \ /    \ /  ___// __ \ 
 |    `   \  | \(  <_> )  / /_/ \  ___/|  | \  ___/|   |  \\___ \\  ___/ 
/_______  /__|   \____/|__\____ |\___  >__|  \___  >___|  /____  >\___  >
        \/                     \/    \/          \/     \/     \/     \/ 


droidefense v0.2 - a tool for automated reverse engineering of Android apk files.
specially focused on Android Malware detection, feature extraction and reporting

Copyright 2017 Droidefense <droidefense@protonmail.com>

2018-01-11 13:13:35 TRACE [main] TRACE:13 - Loading Droidefense environment...
2018-01-11 13:13:35 DEBUG [main] DEBUG:20 - Reading config file: /root/droidefense/config/config.linux.json
usage: droidefense
 -d,--debug                 print debugging information
 -h,--help                  print this message
 -i,--input <apk>           input .apk to be analyzed
 -o,--output <format>       select prefered output: [json, json.min]
 -p,--profile               Wait for JVM profiler
 -s,--show                  show generated report after scan
 -u,--unpacker <unpacker>   select prefered unpacker: [zip, apktool,
                            memapktool]
 -v,--verbose               be verbose
 -V,--version               show current version information

For additional info, please visit: https://github.com/droidefense/engine

root@GBiagomba-Kali:/opt/TEST/engine/target#

**Comment by zerjioang** [comment]
Hi, thanks for your response, and dont worry, you are welcome.
For any other problem you have, just open another issue. :+1:
